# action.yml
name: 'bartvanackooij.com init'
description: 'Set up the basics'
inputs:
  github_token:
    description: 'GitHub API token.'
    required: true
    default: ''
  github_pr_number:
    description: 'GitHub PR number.'
    required: true
    default: ''
runs:
  using: docker
  image: ../data/Dockerfile
  entrypoint: /entrypoints/actions-init.sh
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_number }}