import argparse
import os
import tools.pr_comment as pr_comment

text = "_This comment is generated by the PR bot._\n\n :+1: Good\n :-1: Bad \n :skull: Pipeline-breaking bad!\n\n-----\n\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--github_token', required=True, help='Your Github Token')
    parser.add_argument('--github_pr_number', required=True, help='Your Github PR ID')
    args = parser.parse_args()
    comment_pr = os.getenv('update_comment')

    github_token = args.github_token
    repository = os.getenv('GITHUB_REPOSITORY')
    pr_number = int(args.github_pr_number)

    if comment_pr:
        pr_comment.new(github_token, repository, pr_number)
        pr_comment.write(github_token, repository, pr_number, text)

if __name__ == '__main__':
    main()