
name: merge

on:
  workflow_call:
    inputs: 
      github_pr_number:
        type: number
        description: 'GitHub PR number.'
        required: true
        default: 0
      working_directory:
        type: string
        description: 'Working directory.'
        required: true
        default: ''

env:
  wd_tf_infra: ${{ inputs.working_directory }}
  update_comment: false

jobs:      
  apply:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ${{ env.wd_tf_infra }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform init
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-init@master
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform plan
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-plan@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform apply
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-apply@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true