
name: pr-checks

on:
  workflow_call:
    inputs: 
      github_pr_number:
        type: number
        description: 'GitHub PR number.'
        required: true
        default: 0
      working_directory:
        type: string
        description: 'Working directory.'
        required: true
        default: ''

env:
  wd_tf_infra: ${{ inputs.working_directory }}
  # will create and update comments in PR. 
  update_comment: true

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ${{ env.wd_tf_infra }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Starting bartvanackooij.com's actions
      uses: bartvanackooij-com/github-actions/.github/actions/actions-init@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform fmt
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-fmt@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}

    - name: Terraform init
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-init@master
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform validate
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-validate@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}

    - name: Terraform plan
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-plan@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform costs
      uses: bartvanackooij-com/github-actions/.github/actions/terraform-costs@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    - name: Open AI summary
      uses: bartvanackooij-com/github-actions/.github/actions/openai-summary@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pr_number: ${{ inputs.github_pr_number }}
        open_ai_key: ${{ secrets.OPEN_AI_KEY }}

    - name: Upload terraform plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ${{ env.wd_tf_infra }}/tfplan
      
